### PR TITLE
Add some locks so multiple writers are not failing all the time.

### PR DESCRIPTION
**Pull request by mihasic**
@damianh and the solution was so close

### CODE REVIEW

**Comment by mihasic** [comment]
Might be good to test different kind of writes simultaneously, not just *VersionAny.

**Comment by damianh** [comment]
:boom: that's awesome!

**Comment by damianh** [comment]
Going to run some more load tests, thanks for the contrib.

**Comment by damianh** [comment]
> Might be good to test different kinds of writes simultaneously, not just *VersionAny.

Yes I'll beef up the suite a lot.

**Pull request merged**
