### PR TITLE
Can't Subscribe to All with Cedar.EventStore.MsSql2008

### PR DESCRIPTION
**Pull request by thefringeninja**
Getting the following when subscribing to all:

```
   System.InvalidOperationException: ValueFactory attempted to access the Value property of this instance.
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Cedar.EventStore.MsSqlEventStore.get_GetStoreObservable() in Z:\BuildAgent\work\4ff892dbd8b3e93e\src\Cedar.EventStore.MsSql2008\MsSqlEventStore.cs:line 180

    private IObservable<Unit> GetStoreObservable => _eventStoreNotifier.Value.Result;
```

I added two passing (?) tests to the build to see if multiple concurrent subscriptions were the problem, but apparently they are not.

### CODE REVIEW

**Comment by thefringeninja** [comment]
It might have something to do with `LazyThreadSafetyMode` but I can't tell.

**Comment by damianh** [comment]
So no idea what the problem is? No repro?

**Comment by thefringeninja** [comment]
None whatsoever. I will bang on the InMem store first. Once that's solid I
will switch to sql.

On Mon, Mar 14, 2016 at 4:56 PM, Damian Hickey <notifications@github.com>
wrote:

> So no idea what the problem is? No repro?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/damianh/Cedar.EventStore/pull/14#issuecomment-196381945>
> .
>



-- 
Sent from my regular computer
http://twitter.com/thefringeninja
http://www.thefringeninja.com/

**Comment by damianh** [comment]
I'll merge this anyway because I think the tests have value. Open a new PR if problem shows itself again.

**Pull request merged**
