### PR TITLE
Add support for PostgreSQL

### PR DESCRIPTION
**Pull request by danbarua**
^ what that says

### CODE REVIEW

**Comment by danbarua** [comment]
This uses the unstable build of Npgsql 3 - might have to do some fiddling around with Nuget .config to get it looking at the unstable feed source here: https://www.myget.org/F/npgsql-unstable

**Comment by damianh** [comment]
@danbarua thanks for this! I've not forgotten it; just haven't had time lately for any oss stuff :(

I need CES, and I need Postgres support, so greatly appreciated :)

**Comment by danbarua** [comment]
I’m putting it into production in a month, kittens might die… or there will be a flurry of PRs while I work the issues out.

--  
Dan Barua

**Comment by danbarua** [comment]
Don't merge this just yet, some more wrinkles to iron out re: concurrency under heavy load.

**Comment by danbarua** [comment]
With that last commit, I'm going to monitor our error queues for a few days and fingers crossed we might be production-ready. :)

**Pull request merged**
